Algoritmo "ex04"
// Disciplina  : Lógica de Programação
// Exercício   : ex04
// Descrição   : Apresenta a média entre os números 8, 9 e 7.
// Autor(a)    : Leticia Moura Lopes Soares
// Data atual  : 24/02/2023
Var

    oito, nove, sete, media: real

Inicio

    oito <- 8
    nove <- 9
    sete <- 7
    media <- (oito + nove + sete) / 3
    escreval("A media entre 8, 9 e 7 é", media)

Fimalgoritmo