Algoritmo "ex08"
// Disciplina  : Lógica de Programação
// Exercício   : ex08
// Descrição   : Recebe nome, endereço e telefone e apresenta
// Autor(a)    : Leticia Moura Lopes Soares
// Data atual  : 24/02/2023
Var

    nome, endereco: caractere
    telefone: inteiro

Inicio

    escreval("Informe seu nome:")
    leia(nome)
    escreval("Informe seu endereço:")
    leia(endereco)
    escreval("Informe seu telefone:")
    leia(telefone)
    escreval( nome , endereco , telefone)

Fimalgoritmo