Algoritmo "ex26"
// Disciplina  : Lógica de Programação
// Exercício   : ex26
// Descrição   : Calcular a área de um triângulo
// Autor(a)    : Leticia Moura Lopes Soares
// Data atual  : 05/03/2023
Var

    base, altura, area, divisao: real

Inicio

    escreval("Informe a base do triângulo")
    leia(base)
    escreval("Informe a altura do triângulo")
    leia(altura)
    
    area <- (base * altura) / 2
    
    escreval("A área do triângulo é:", area)

Fimalgoritmo