Algoritmo "ex28"
// Disciplina  : Lógica de Programação]
// Exercício   : ex28
// Descrição   : Entrar com nome e idade e imprimir na tela
// Autor(a)    : Leticia Moura Lopes Soares
// Data atual  : 05/03/2023
Var

    nome: caractere
    idade: inteiro

Inicio

    escreval("Digite seu nome:")
    leia(nome)
    escreval("Digite sua idade:")
    leia(idade)
    
    escreval("Nome:", nome)
    escreval("Idade:", idade)

Fimalgoritmo