Algoritmo "ex06"
// Disciplina  : Lógica de Programação
// Exercício   : ex06
// Descrição   : Ler e apresentar dois números inteiros.
// Autor(a)    : Leticia Moura Lopes Soares
// Data atual  : 24/02/2023
Var

    num1, num2: inteiro

Inicio

    escreval("Informe o primeiro número inteiro")
    leia(num1)
    escreval("Informe o segundo número inteiro")
    leia(num2)
    escreval(num1, "e", num2)

Fimalgoritmo