Algoritmo "ex10"
// Disciplina  : Lógica de Programação
// Exercício   : ex10
// Descrição   : Receber dois números inteiros e apresentar o produto
// Autor(a)    : Leticia Moura Lopes Soares
// Data atual  : 24/02/2023
Var

    num1, num2, produto: inteiro

Inicio

    escreval("Informe um número")
    leia(num1)
    escreval("Informe outro número")
    leia(num2)
    produto <- num1 * num2
    escreval("O produto é", produto)

Fimalgoritmo